import React from 'react';
import { ChevronRight, ChevronLeft, CheckCircle2, Target } from 'lucide-react';

interface AITrainingPageProps {
  onNext: () => void;
  onBack: () => void;
}

export function AITrainingPage({ onNext, onBack }: AITrainingPageProps) {
  const trainingSteps = [
    'Real questions visitors ask',
    'Suggested responses generated by Halda',
    'Simple ways to confirm, improve, or adjust those responses'
  ];

  const trainingBenefits = [
    'Improve response accuracy',
    'Reduce confusion for families',
    'Keep information aligned with your school',
    'Increase confidence in automated responses'
  ];

  const supportAreas = [
    'Answer questions about training',
    'Share best practices',
    'Review progress',
    'Recommend ways to improve results'
  ];

  const timeCommitments = [
    { period: 'About 1 hour per week', duration: 'during the first 3–4 weeks' },
    { period: 'About 10–30 minutes per week', duration: 'after that' }
  ];

  return (
    <div className="min-h-screen" style={{ backgroundColor: '#f8f9fa' }}>
      <div className="max-w-7xl mx-auto px-8 py-12">
        {/* Page Title */}
        <h1 className="text-center mb-10 text-4xl">
          AI training
        </h1>

        {/* Main Content Card */}
        <div className="bg-white rounded-lg p-10 mb-6">
          {/* Primary Goal Section */}
          <div className="mb-16 max-w-4xl mx-auto">
            <div className="relative pl-8">
              <div className="absolute left-0 top-0 bottom-0 w-1 rounded-full" style={{ backgroundColor: '#ffdf44' }}></div>
              <h2 className="mb-4 text-3xl" style={{ color: '#0e1016' }}>
                Primary goal
              </h2>
              <p className="text-gray-700 text-lg">
                Explain why training matters, set realistic expectations for time and effort, and encourage partners to begin practicing right away.
              </p>
            </div>
          </div>

          {/* Intro Video Section */}
          <div className="mb-16 max-w-5xl mx-auto">
            <div className="rounded-xl overflow-hidden border-2" style={{ borderColor: '#ffdf4466', backgroundColor: '#ffffff' }}>
              <div className="aspect-video flex items-center justify-center" style={{ backgroundColor: '#0e101611' }}>
                <div className="text-center px-8">
                  <div className="w-20 h-20 rounded-full mx-auto mb-4 flex items-center justify-center" style={{ backgroundColor: '#ffdf4499' }}>
                    <div className="w-0 h-0 border-l-[16px] border-l-white border-t-[10px] border-t-transparent border-b-[10px] border-b-transparent ml-1"></div>
                  </div>
                  <p className="text-gray-600">
                    Intro video: What AI Training is and why it matters
                  </p>
                </div>
              </div>
            </div>
            <p className="text-gray-600 text-sm mt-3 max-w-4xl mx-auto">
              <strong>Video covers:</strong> What AI Training is, why training improves accuracy and usefulness over time, how small consistent practice leads to better results, and what "good" training looks like in the first few weeks. Tone: Encouraging, practical, and non-technical. Emphasize progress over perfection.
            </p>
          </div>

          {/* Intro Copy */}
          <div className="mb-16 max-w-4xl mx-auto">
            <p className="text-gray-700 mb-4 text-lg">
              Halda becomes more helpful over time as it learns from real questions and interactions.
            </p>

            <p className="text-gray-700 mb-4 text-lg">
              AI Training is how you guide that learning. By spending a small amount of time each week, you help Halda respond more accurately and more consistently to the questions families actually ask.
            </p>

            <p className="text-gray-700 text-lg">
              This page explains what training involves and what to expect.
            </p>
          </div>

          {/* Divider */}
          <div className="max-w-4xl mx-auto mb-16">
            <div className="h-px" style={{ backgroundColor: '#0e101622' }}></div>
          </div>

          {/* What is AI Training Section */}
          <div className="mb-16 max-w-5xl mx-auto">
            <div className="rounded-xl p-8" style={{ backgroundColor: '#4fabff22', borderLeft: '4px solid #4fabff' }}>
              <h2 className="mb-6 text-2xl" style={{ color: '#0e1016' }}>
                What is AI Training?
              </h2>

              <p className="text-gray-700 mb-6 text-lg">
                AI Training is the process of reviewing and improving how Halda responds to questions and prompts.
              </p>

              <p className="mb-4" style={{ color: '#0e1016' }}>You'll see:</p>
              <ul className="space-y-2 mb-6">
                {trainingSteps.map((step, index) => (
                  <li key={index} className="flex gap-3 items-start">
                    <span className="text-gray-700">• {step}</span>
                  </li>
                ))}
              </ul>

              <p className="text-gray-700 text-lg">
                Training helps ensure the information families receive matches your school's voice, priorities, and expectations.
              </p>
            </div>
          </div>

          {/* Why training matters Section */}
          <div className="mb-16 max-w-4xl mx-auto">
            <h2 className="mb-6 text-2xl" style={{ color: '#0e1016' }}>
              Why training matters
            </h2>

            <p className="mb-4" style={{ color: '#0e1016' }}>Regular training helps:</p>
            <ul className="space-y-2 mb-6">
              {trainingBenefits.map((benefit, index) => (
                <li key={index} className="flex gap-3 items-start">
                  <CheckCircle2 className="w-5 h-5 flex-shrink-0 mt-0.5" style={{ color: '#4fabff' }} />
                  <span className="text-gray-700 text-lg">{benefit}</span>
                </li>
              ))}
            </ul>

            <p className="text-gray-700 text-lg">
              The more Halda is trained, the more helpful it becomes.
            </p>
          </div>

          {/* Divider */}
          <div className="max-w-4xl mx-auto mb-16">
            <div className="h-px" style={{ backgroundColor: '#0e101622' }}></div>
          </div>

          {/* What to expect for time commitment Section */}
          <div className="mb-16 max-w-4xl mx-auto">
            <div className="relative pl-8">
              <div className="absolute left-0 top-0 bottom-0 w-1 rounded-full" style={{ backgroundColor: '#907fff' }}></div>
              <h2 className="mb-6 text-2xl" style={{ color: '#0e1016' }}>
                What to expect for time commitment
              </h2>

              <p className="text-gray-700 mb-6 text-lg">
                AI Training works best when it's consistent, not intensive.
              </p>

              <p className="mb-4" style={{ color: '#0e1016' }}>Typical expectations:</p>
              <ul className="space-y-3 mb-6">
                {timeCommitments.map((commitment, index) => (
                  <li key={index} className="flex gap-3 items-start">
                    <span className="text-gray-700 text-lg">
                      • <strong>{commitment.period}</strong> {commitment.duration}
                    </span>
                  </li>
                ))}
              </ul>

              <p className="text-gray-700 text-lg">
                Training can be done in short sessions and does not require technical skills.
              </p>
            </div>
          </div>

          {/* Divider */}
          <div className="max-w-4xl mx-auto mb-16">
            <div className="h-px" style={{ backgroundColor: '#0e101622' }}></div>
          </div>

          {/* Getting started with training Section */}
          <div className="mb-16 max-w-5xl mx-auto">
            <div className="rounded-xl p-8" style={{ backgroundColor: '#ffdf4422', borderLeft: '4px solid #ffdf44' }}>
              <h2 className="mb-6 text-2xl" style={{ color: '#0e1016' }}>
                Getting started with training
              </h2>

              <p className="text-gray-700 mb-8 text-lg">
                To get familiar with AI Training, we recommend starting right away.
              </p>

              <div className="rounded-lg p-6 mb-6" style={{ backgroundColor: '#ffffff', border: '2px solid #ffdf4466' }}>
                <div className="flex items-start gap-4">
                  <Target className="w-8 h-8 flex-shrink-0 mt-1" style={{ color: '#ffdf44' }} />
                  <div>
                    <h3 className="mb-3 text-xl" style={{ color: '#0e1016' }}>Action</h3>
                    <p className="text-gray-700 text-lg">
                      Practice training at least <strong>three questions</strong> in the AI Training Dashboard.
                    </p>
                    <p className="text-gray-700 text-lg mt-3">
                      This will help you understand the workflow and build early momentum.
                    </p>
                  </div>
                </div>
              </div>

              <p className="text-gray-600 text-sm">
                There's no "right" or "wrong" way to start. The goal is simply to get comfortable.
              </p>
            </div>
          </div>

          {/* Ongoing support Section */}
          <div className="mb-16 max-w-4xl mx-auto">
            <h2 className="mb-6 text-2xl" style={{ color: '#0e1016' }}>
              Ongoing support
            </h2>

            <p className="mb-4" style={{ color: '#0e1016' }}>Your account manager can help:</p>
            <ul className="space-y-2 mb-6">
              {supportAreas.map((area, index) => (
                <li key={index} className="flex gap-3 items-start">
                  <span className="text-gray-700 text-lg">• {area}</span>
                </li>
              ))}
            </ul>

            <p className="text-gray-700 text-lg">
              You're not expected to figure this out on your own.
            </p>
          </div>

          {/* Divider */}
          <div className="max-w-4xl mx-auto mb-16">
            <div className="h-px" style={{ backgroundColor: '#0e101622' }}></div>
          </div>

          {/* Before You Continue */}
          <div className="mb-12 max-w-4xl mx-auto">
            <div className="relative pl-8">
              <div className="absolute left-0 top-0 bottom-0 w-1 rounded-full" style={{ backgroundColor: '#fe8576' }}></div>
              <h2 className="mb-4 text-2xl" style={{ color: '#0e1016' }}>
                Before you continue
              </h2>
              <p className="text-gray-700 mb-4 text-lg">
                AI Training is an ongoing part of using Halda, not a one-time task.
              </p>
              <p className="text-gray-700 text-lg">
                Starting early helps ensure families receive helpful, accurate responses from day one.
              </p>
            </div>
          </div>

          {/* CTA Section */}
          <div className="max-w-4xl mx-auto">
            <div className="rounded-lg p-8" style={{ backgroundColor: '#ffdf4499' }}>
              <div className="flex items-center justify-center gap-4 mb-3">
                <button
                  onClick={onBack}
                  className="text-white px-8 py-3 rounded transition-all inline-flex items-center gap-2 text-lg hover:opacity-90"
                  style={{ backgroundColor: '#0e1016' }}
                >
                  <ChevronLeft className="w-5 h-5" />
                  Back
                </button>

                <button 
                  onClick={onNext}
                  className="text-white px-8 py-3 rounded transition-all inline-flex items-center gap-2 text-lg hover:opacity-90"
                  style={{ backgroundColor: '#0e1016' }}
                >
                  Continue to account management and next steps
                  <ChevronRight className="w-5 h-5" />
                </button>
              </div>

              <p className="text-gray-600 text-sm text-center">
                You can pause and return at any time.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}